### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pelanas**
Avoiding unnecessary public key validation can be useful for newbies as me.

### CODE REVIEW

**Comment by TiBeN** [comment]
Thank you for your contribution!
Beware if you plan to really try and use this package as it can be a little outdated depending on the ubuntu version you use. It was made during the 15.10 Wily Werewolf Ubuntu era. 
I'm in the process of the rewriting the documentation, specially improving the Xorg configuration layouts to be more exaustive. In between, Ubuntu Xenial is out. I tried it and now things becomes easier: 
- Nvidia NOUVEAU drivers 1.0.12 worked flawlessly on low resolutions without having to patch thems
- Linux kernel patching is only required with ATI/arcade vga cards and KMS support (which can only be required for one screen setup, not for the master/slave two screens setup this repository primarily fosuses on)
- Since 0.172, groovymame seems to be merged with Mame upstream (need to be confirmed) .

So, this project is not dead, but i have some work to refresh it!

**Comment by pelanas** [comment]
Thank you for you answer. I'm trying to seup an arcade cabinet the hard way
since i'm new to linux and github... but i like a lot your work... it is
more like hard learning lessons. I'd like to contribute and make it working
again in wily. now I'm having trouble with vice dependencies and his lines
in Makefile file.

I have limited time but im learning a lot with this and i'll be thanked if
you have some patience with me. Sorry for my spanish english.

Regards,

 Juanvi

2016-05-15 13:55 GMT+02:00 Benjamin Legendre notifications@github.com:

**Comment by TiBeN** [comment]
Hi juanvi, 
I'm Glad you like this project. I'm practicing Linux for years. If you like computing and invest some times on Linux you will be rewarded. I think doing what you want is a good start to learn. The difficult part is, i think, the setup of xorg. Xorg is an old beast and has sometimes weird behaviour which is difficult to understand and, more generally the graphic stack on Linux is pretty complex. 
I was busy theses times but i'm planning to work on this repo to makes it at least compatible with Ubuntu Xenial. I'm planning to dedicate an old pc too for this purpose so i'll spend some times to enrich the Xorg Single screen layout part of the documentation. 

So if you are motivated to contribute to the project, feel free to send you pull request.
And if you like it, you can star it!

**Comment by pelanas** [comment]
Thanks for your friendly words. I'll try to start my arcade cab with your
project always staying with Ubuntu 15.10. I do not understand the benefits
of going Xenial. If you agree with my little contributions i'd like to
continue sending you pull requests.
I'm removilng all vice related because make fails at some point... and .170
mame is my target.  Thanks for all.

2016-05-19 8:25 GMT+02:00 Benjamin Legendre notifications@github.com:

**Comment by TiBeN** [comment]
OK. It could be better for upstream version (master branch) to keep vice stuff and try to debug instead of removing the feature. I'll take a look asap. But feel free to make a fork if you want to maintain your own changes.
I'm plan to make somes deeper tests to make sure patching nouveau drivers is not required anymore in actual version 1.0.12 (wily and xenial) and remove this step from the makefile. After that i think the time will come to release a stable version for Wily and go forward to xenial.
As you said there are no big changes in between but it is important to stay in sync and up to date, at least to be sure to have needed dependencies availables (to use latest emulators versions for example).

I'll add on the repo a TODO.md file which i maintain locally to make the direction of the project explicit.
Thank you for your interest.

**Comment by pelanas** [comment]
Always thinking about removing stuff only in my ,already done, fork
respecting yours. I understand your direction. Thaks for your patience.

**Comment by TiBeN** [comment]
About Vice support, maybe you could open an issue with a description of the problem ?

**Comment by pelanas** [comment]
I'll do. I'm not familiar with github basics yet.

2016-05-19 13:41 GMT+02:00 Benjamin Legendre notifications@github.com:

**Pull request merged**
