### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by pelanas**
Ok. I saw the mistake in previous pull request.

### CODE REVIEW

**Comment by TiBeN** [comment]
Using the github as provider instead of the mamedev official website is a good idea, but their is a problem with your pull request, you should take the zipped source release instead of the exe one because "exe" files is windows binary file and not linux compatible. I have not tried the "groovymame" target of the makefile but i'm pretty sure it fails. Maybe the exe version is an embedded zip and makes the target works, but in all case it is not good linux dev practice.

**Comment by pelanas** [comment]
Wow! What fast answer! You are right but official website has not worked
when I tested it, because thath I've pointer thath way. I'lltry to find the
zipped in GitHub.

2016-05-19 13:15 GMT+02:00 Benjamin Legendre notifications@github.com:

**Comment by TiBeN** [comment]
all releases are listed here:
https://github.com/mamedev/mame/releases

**Comment by pelanas** [comment]
This could work?
https://github.com/mamedev/mame/archive/mame0171.zip

2016-05-19 13:30 GMT+02:00 Benjamin Legendre notifications@github.com:

**Comment by pelanas** [comment]
Sorry, this:
https://github.com/mamedev/mame/archive/mame0170.zip
Could work?

2016-05-19 13:41 GMT+02:00 Juanvi Pastor pastor.juanvi@gmail.com:

**Comment by TiBeN** [comment]
yes it's the good source package.

**Comment by pelanas** [comment]
I've added new commit with this.

2016-05-19 13:42 GMT+02:00 Benjamin Legendre notifications@github.com:

**Comment by TiBeN** [comment]
Sorry i didn't carrefully looked at your URL. The good URL is the following:
https://github.com/mamedev/mame/releases/download/mame0170/mame0170s.zip

If you notice the "s" at the end, it means "source". That's the official source release. The one you take is not made by the team but automatically generated by github when they declare the release. It might works but is not official. 
Despite this i took a look on your pull request and it seems to be good. Don't forget to try and make sure it compiles before sending your pull request by doing "make groovymame" on a fresh source tree (or after done a make clean).
Thanks

**Comment by TiBeN** [comment]
Hi, your last pull request includes a lot changes which are not related to the Mame source URL (it's an error i think).
I suggest to recreate a clean new pull request for the initial purpose and close this one. 
Thanks

**Comment by pelanas** [comment]
Sorry for the inconvenience. I was sure about making changes in my fork for
personal use but I was wrong. Instead of this I was subbmitting pull
requests to you. I'm new to github and I'm falling in lots of mistakes.
Thanks

2016-05-25 10:00 GMT+02:00 Benjamin Legendre notifications@github.com:

**Comment by TiBeN** [comment]
don't worry, no problem :)
I think you should do a clean "git clone" on a new folder with the github url of your fork to work on it. 
But i should be wrong as a i've never worked on fork.

**Pull request closed without merging**
